FROM python:3.11-slim

WORKDIR /src

RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir cog

COPY model_cifar10_optimized.pth .
COPY predict_cifar10_optimized.py .

EXPOSE 5000

CMD ["python", "-m", "cog.server.http"]
