services:
  cog-api:
    build:
      context: .
      dockerfile: Dockerfile.cog
    ports:
      - "5001:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict.py:Predictor

  cog-api-optimized:
    build:
      context: .
      dockerfile: Dockerfile.cog.optimized
    ports:
      - "5002:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict_optimized.py:Predictor

  cog-api-cifar10:
    build:
      context: .
      dockerfile: Dockerfile.cog.cifar10
    ports:
      - "5003:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict_cifar10.py:Predictor

  cog-api-cifar10-optimized:
    build:
      context: .
      dockerfile: Dockerfile.cog.cifar10.optimized
    ports:
      - "5004:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict_cifar10_optimized.py:Predictor

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://cog-api:5000/predictions
      - API_URL_OPTIMIZED=http://cog-api-optimized:5000/predictions
      - API_URL_CIFAR10=http://cog-api-cifar10:5000/predictions
      - API_URL_CIFAR10_OPTIMIZED=http://cog-api-cifar10-optimized:5000/predictions
    depends_on:
      - cog-api
      - cog-api-optimized
      - cog-api-cifar10
      - cog-api-cifar10-optimized
