services:
  cog-api:
    build:
      context: .
      dockerfile: Dockerfile.cog
    ports:
      - "5001:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict.py:Predictor

  cog-api-optimized:
    build:
      context: .
      dockerfile: Dockerfile.cog.optimized
    ports:
      - "5002:5000"
    environment:
      - COG_PREDICT_TYPE_STUB=predict_optimized.py:Predictor

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://cog-api:5000/predictions
      - API_URL_OPTIMIZED=http://cog-api-optimized:5000/predictions
    depends_on:
      - cog-api
      - cog-api-optimized
